# Generated by Django 5.1.3 on 2024-12-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='org',
            new_name='organization',
        ),
    ]
