# Generated by Django 5.1.3 on 2024-12-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lastivent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastivent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lastivent',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lastivent',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lastivent',
            name='discipline',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lastivent',
            name='format',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lastivent',
            name='mens',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lastivent',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
