# Generated by Django 5.1.3 on 2024-12-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_lastivent_city_alter_lastivent_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastivent',
            name='date_end',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lastivent',
            name='date_start',
            field=models.DateField(blank=True, max_length=250, null=True),
        ),
    ]
