# Generated by Django 5.1.3 on 2024-12-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lastivent_date_end_alter_lastivent_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastivent',
            name='date_start',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
