# Generated by Django 5.1.3 on 2024-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_lastivent_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastivent',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lastivent',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
