# Generated by Django 5.1.2 on 2024-12-06 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_organization_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(to='main.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization')),
            ],
        ),
        migrations.CreateModel(
            name='personaEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(to='main.event')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.persona')),
            ],
        ),
    ]
