# Generated by Django 5.1.2 on 2024-12-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_organizationsevents_personaevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='fio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sex',
            field=models.CharField(blank=True, choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=250, null=True),
        ),
    ]
