# Generated by Django 5.1.2 on 2024-12-07 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_organization_fio_alter_persona_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolls', models.IntegerField()),
                ('problems', models.TextField()),
                ('helpers', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.persona')),
            ],
        ),
    ]
