# Generated by Django 5.1.2 on 2024-12-07 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_report_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.persona')),
            ],
        ),
        migrations.AddField(
            model_name='personaevents',
            name='comments',
            field=models.ManyToManyField(to='main.comment'),
        ),
    ]
