# Generated by Django 5.1.3 on 2026-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
